name: CI/CD Pipeline (Remote Docker Build)

on:
  push:
    branches: [ "main" ]   # Runs when you push to main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for Maven build)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Step 3: Build your Spring Boot JAR
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker image using your Dockerfile
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/skysmart-app:latest .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/skysmart-app:latest
